### ISSUE TITLE
Typo or intentional?

### ISSUE THREAD

**Issue by stdarg** [StoicPerlman/falcon-openapi#1]
I saw this in router.py. Look at the last line:

```python
class OpenApiRouter(CompiledRouter):
    def __init__(self, file_path='openapi-spec.yml', raw_json='', raw_yaml=''):
        super().__init__()

        if raw_json != '':
            self.openapi = json.loads(raw_json)
        elif raw_yaml != '':
            self.openapi = yaml.load(raw_yaml)
        else:
            if not Path(file_path).exists() and file_path == 'openapi-spec.yml':
                file_path = 'openapi-spec.yaml'
```

It seems that, if the user specified "openapi-spec.yml," they did not mean "openapi-spec.yaml."

**Comment by stdarg** [comment]
Apparently, this site: http://yaml.org/faq.html, believes "yaml" is more correct, too.

**Comment by StoicPerlman** [comment]
It was intentional, but I see your point. I wanted a way so if no file was supplied it would default to openapi-spec.yml and fall back to openapi-spec.yaml. But if a user specifies openapi-spec.yml I could see how confusion could arise. Perhaps I could change it to

```python
class OpenApiRouter(CompiledRouter):
    def __init__(self, file_path='', raw_json='', raw_yaml=''):
        super().__init__()

        if raw_json != '':
            self.openapi = json.loads(raw_json)
        elif raw_yaml != '':
            self.openapi = yaml.load(raw_yaml)
        elif file_path == '':
            file_path = 'openapi-spec.yml'

            if not Path(file_path).exists():
                file_path = 'openapi-spec.yaml'

            if not Path(file_path).exists():
                Exception("Unable to find openapi-spec.yml or openapi-spec.yaml")
```

**Comment by stdarg** [comment]
That would be less confusing. Your example on the readme has ".yml", which is how I stumbled on the issue.

**Comment by StoicPerlman** [comment]
ah yes. I wrote the readme before making that change. I should update that too. Thanks for pointing it out.

**Comment by stdarg** [comment]
No worries. I'm hoping to get this working at work. I like the implementation. I'll let you know how it goes.

**Comment by StoicPerlman** [comment]
Let me know if this update addresses everything. Also, if you have any other feedback I would be happy to hear it.

**Comment by stdarg** [comment]
Yes, that works. Thanks.

**Comment by stdarg** [comment]
After testing the basePath, I found that too, doesn't work, unfortunately.
