### ISSUE TITLE
URI path from servers not obeyed?

### ISSUE THREAD

**Issue by stdarg** [StoicPerlman/falcon-openapi#3]
I created a new example while testing out. As an aside, you are free to use this example for your project. I think it would be useful to show people that you need to qualify that the controllers are a part of the falcon-openapi module and importing from the users' own module to the falcon-openapi controllers need to be properly qualified on the import.

The problem I'm having is that the servers URI path is not being obeyed in the YAML file, e.g.:

```yaml
---
info:
  version: 0.0.0
  title: Example
  license:
    name: MIT
servers:
  - url: http://localhost/example/v1
paths:
    "/health":
        get:
            summary: A simple health check.
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    name: string
                                    version: string
                                    git_hash: string
            x-falcon:
                module: controllers.health
                class: HealthCheck
                method: on_get
```

I expect to need to access the controller with the URI: `http://localhost:8000/example/v1/health` but only `http://localhost:8000/health`works. Is this by design? I didn't have time to look at the implementation. You can see the sample project [here](https://github.com/stdarg/falcon-openapi-example).

**Comment by StoicPerlman** [comment]
I will add this. In the handful of apps I have running with this I haven't actually used the server definition to define a prefix so I didn't think about it.

Are you worried about openapi v2 support? If not I may skip adding the basePath prefix and just worry about the servers->url that replaced it in v3.

This is roughly based on this [Mojo plugin](https://metacpan.org/pod/Mojolicious::Plugin::OpenAPI) I use at work. I want to look into how they handle the case of multiple servers being defined and those servers have different paths. At my work we are still using openapi v2 so this hasn't been an issue as it still has the basePath.

**Comment by stdarg** [comment]
I thought I was using servers.url? I'd suggest v3. But if this is a v2 plugin, I'll use basePath.

**Comment by stdarg** [comment]
One comment, if this requires the use of Swagger 2.0, I wouldn't name it OpenApi, as that's the 3.0 specification. OpenApi implies it supports Swagger 3.0, AKA OpenApi 3.0.

**Comment by StoicPerlman** [comment]
I was only planning on supporting v3. I was asking about v2 to see if you needed it. I am going to add support for servers.url. I am researching now how to handle multiple servers that may have different paths defined.

**Comment by StoicPerlman** [comment]
It would be easiest just to use the first one. I could always add support for extra later. Where I work its common to have http://localhost/v1, http://qa.company.com/app_name/v1, and http://company.com/app_name/v1. After hitting a proxy the app_name is stripped so the end application only sees /v1, but we still need to list all proper servers in the spec.

**Comment by StoicPerlman** [comment]
After looking at some examples in other frameworks I decided to take the path from the first url in the servers list. If anyone needs something else, open an issue with your use case and how it should work.
