### ISSUE TITLE
High severity security vulnerability

### ISSUE THREAD

**Issue by stdarg** [StoicPerlman/falcon-openapi#4]
✗ High severity vulnerability found in pyyaml
  Description: Arbitrary Code Execution
  Info: https://snyk.io/vuln/SNYK-PYTHON-PYYAML-42159
  Introduced through: falcon-openapi@0.2.0
  From: falcon-openapi@0.2.0 > pyyaml@3.13

**Comment by StoicPerlman** [comment]
What did you use to generate this? Pipenv check passed.

Also it looks like pyyaml pulled 4.1 back. So unless I change to a different module, or pin the pre release, there isn't much I can do.

**Comment by StoicPerlman** [comment]
I see it's a whole continuous security platform.

**Comment by StoicPerlman** [comment]
Switched this to use safe_load which was the mitigation done for yaml.load in 4.1. Snyk will still alert for it though it looks like.
